---
title: "ECS 132 - Project"
author: Teresa Li, sqtli@ucdavis.edu \break Wenjing Fu, luffu@ucdavis.edu
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\pagebreak[4]

# Design

## Question 1
```{r Q1}
Traffic_data_orig <- read.csv("Traffic_data_orig.csv", header=TRUE)
message <- "this is a secret message"
raw <- charToRaw(message)
time = Traffic_data_orig$Time
num = as.integer(rawToBits(raw))

delays = numeric(length(time) - 1)
for (i in (1:(length(time) - 1))) {
  delays[i] = time[i+1] - time[i]
}

index = 1
bitlen = length(raw)*8
encrpt <- numeric(length(raw)*8)
for (i in (0:(length(raw)-1))) {
  for (j in 1:8) {
    if (num[i*8+j] == 0) {
      encrpt[index] = 0.25
    }
    else {
      encrpt[index] = 0.75
    }
    index = index+1
    j = j-1
  }
}

delays2 = delays
for (i in (1:bitlen)) {
  delays2[i] = encrpt[i]
}
```


## Question 2
```{r Q2, dependson='Q1'}
hist(delays, col='grey', xlab = 'Delay Time', 
     main = 'Histogram of Overt Packet Stream')
hist(delays2, col='grey', xlab = 'Delay Time', 
     main = 'Histogram of Convert Packet Stream')
```
Yes, Eve will be suspicious because it is obvious that the distribution changed.

## Question 3

```{r Q3}
Traffic_data_orig <- read.csv("Traffic_data_orig.csv", header=TRUE)
message <- "this is a secret message"
raw <- charToRaw(message)
time = Traffic_data_orig$Time
num = as.integer(rawToBits(raw))
delays = numeric(length(time) - 1)
for (i in (1:(length(time) - 1))) {
  delays[i] = time[i+1] - time[i]
}
m = median(delays)
max = max(delays)
min = min(delays)

index = 1
bitlen = length(raw)*8
encrpt <- numeric(length(raw)*8)
for (i in (0:(length(raw)-1))) {
  for (j in 1:8) {
    if (num[i * 8 + j] == 0) {
      encrpt[index] = runif(1, min, m)
    }
    else {
      encrpt[index] = runif(1, m, max)
    }
    index = index + 1
    j = j - 1
  }
}

delays2 = delays
for (i in (1:bitlen)) {
  delays2[i] = encrpt[i]
}
```

## Question 4
```{r Q4, dependson='Q3'}
hist(delays, col='grey', xlab = 'Delay Time', 
     main = 'Histogram of Overt Packet Stream')
hist(delays2, col='grey', xlab = 'Delay Time', 
     main = 'Histogram of Convert Packet Stream')
```
I think Eva will not be suspicious.

## Question 5

1. Instead of generating random number from m to max, and min to m, we can choose one of the existing one from m to max, and min to m.
2. 
3. 

# Detection

## Steps 1

```{r S1}

```




